version: '3'
services:
  spring-logs:
    image: spring-logs:latest 
    ports:
    - "8080:8080"
    volumes:
    - "/var/log:/var/log"
  filebest-logs:
    image: docker.elastic.co/beats/filebeat:6.5.1
    volumes:
    - "/root/pro/filebeat/filebeat-logstash.yml:/usr/share/filebeat/filebeat.yml"
    - "/var/log:/var/log"
    - "/root/pro/filebeat/registry:/usr/share/filebeat/data/registry"
